config/routes.rb
Template::Application.routes.draw do
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  get "project/index"
  get "portfolio/index"
  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'

   root 'home#index'

  

end

app/models/user.rb
class User < ActiveRecord::Base
  before_save {self.email = email.downcase}
  validates :name, presence: true, length: {maximum: 50}
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, format: {with: VALID_EMAIL_REGEX}, uniqueness: {case_sensitive: false}
  has_secure_password
  validates :password, length: {minimum: 8}

  def User.new_remember_token
    SecureRandom.urlsafe_base64

  end

  def feed
    Micropost.where("user_id = ?", id)
  end

  def feed
    Micropost.from_users_followed_by(self)
  end


  def User.digest(token)
    Digest::SHA1.hexdigest(token.to_s)
  end
  def following?(other_user)
    relationships.find_by(followed_id: other_user.id)
  end

  def follow!(other_user)
    relationships.create!(followed_id: other_user.id)
  end

  def unfollow!(other_user)
    relationships.find_by(followed_id: other_user.id).destroy
  end

  private

  def create_remember_token
    self.remember_token = User.digest(User.new_remember_token)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :signed_in_user, only: [:index, :edit, :update, :destroy]
  before_action :correct_user,   only: [:edit, :update]
  
  def show
    @user = User.find(params[:id])
  end
  def new
    @user = User.new

  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = "Registro actualizado"
      redirect_to @user

    else
      render 'edit'
    end
  end
  def create
    @user = User.new(user_params)
    if @user.save
      sign_in @user
      flash[:success] = "Welcome !"
      redirect_to @user
    else
      render 'new'
    end
  end


 



  private

  def user_params
    params.require(:user).permit(:name, :email, :password,
                                 :password_confirmation)
  end

  def signed_in_user
      unless signed_in?
        store_location
        redirect_to signin_url, notice: "Please sign in."
      end
    end

    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless current_user?(@user)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<div class="container content">
  <div class="row">
    
    <div class="col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2 reg-page">
      <div class="reg-header">
                        <h2>Register a new account</h2>
                        <p>Already Signed Up? Click <%= link_to "Sign in", signin_path %>  to login your account.</p>                    
                    </div>

      <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>
      <%= f.label :name, "Nombre" %>
      <%= f.text_field :name, class: 'form-control margin-bottom-20', placeholder:"Nombre" %>
      <%= f.label :email %>
      <%= f.text_field :email, :autofocus => false, class: 'form-control margin-bottom-20', placeholder:"Email" %>
      <%= f.label :password, " Contraseña" %>
      <%= f.password_field :password, autocomplete: "off", :class => "form-control margin-bottom-20", placeholder:"Contraseña" %>
      <%= f.label :password_confirmation, "Confirmar contraseña" %>
      <%= f.password_field :password_confirmation, :class => "form-control margin-bottom-20" %></br></br>
      <div class="col-lg-5 text-right">
      
        <% if params[:action] ==  "new" || params[:action] == "create"%>
        <%= f.submit "Create my account", class: "btn btn-large btn-primary" %>
          
      <%else%>

      <%= f.submit "Save changes",  class: "btn btn-large btn-primary" %>

      <%end%>
      </div>
      
      <% end %>
      
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %>
<h1>Update your profile</h1>
<%= render 'users/form' %>

app/views/users/new.html.erb
<% provide(:title, "Sign up") %>
 <%= render 'users/form' %>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>

  <aside class="span4">
    <section>
      <h1>
        <%= @user.name %>
      </h1>
    </section>
  </aside>